on: push

jobs:
  check:
    runs-on: ubuntu-latest
    container: andeo1812/meetup_project_cpp
    steps:
      - uses: actions/checkout@v2
      - run: make check
  build:
    runs-on: ubuntu-latest
    container: andeo1812/meetup_project_cpp
    needs: [check]
    steps:
      - uses: actions/checkout@v2
      - run: make build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: build/project/HttpServer
  test_context:
    runs-on: ubuntu-latest
    container: andeo1812/meetup_project_cpp
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - run: make test_context
  coverage_test_context:
    runs-on: ubuntu-latest
    container: andeo1812/meetup_project_cpp
    needs: [ test_context ]
    steps:
      - uses: actions/checkout@v2
      - run: make test_context
  memtest_context:
    runs-on: ubuntu-latest
    container: andeo1812/meetup_project_cpp
    needs: [ coverage_test_context ]
    steps:
      - uses: actions/checkout@v2
      - run: make test_context
  test_parsing:
    runs-on: ubuntu-latest
    container: andeo1812/meetup_project_cpp
    needs: [memtest_context]
    steps:
      - uses: actions/checkout@v2
      - run: make test_parsing;
  coverage_test_parsing:
    runs-on: ubuntu-latest
    container: andeo1812/meetup_project_cpp
    needs: [ test_parsing ]
    steps:
      - uses: actions/checkout@v2
      - run: make test_context
  memtestest_parsing:
    runs-on: ubuntu-latest
    container: andeo1812/meetup_project_cpp
    needs: [ coverage_test_parsing ]
    steps:
      - uses: actions/checkout@v2
      - run: make test_context
  test_database:
    runs-on: ubuntu-latest
    container: andeo1812/meetup_project_cpp
    needs: [ memtest_context ]
    steps:
      - uses: actions/checkout@v2
      - run: make test_database;
