#on: push

jobs:
  check:
    runs-on: ubuntu-latest
    container: andeo1812/gcc_check_gtest
    steps:
      - uses: actions/checkout@v2
      - run: make check
  build:
    runs-on: ubuntu-latest
    container: andeo1812/gcc_check_gtest
    needs: [check]
    steps:
      - uses: actions/checkout@v2
      - run: make build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: build/HW-2
  test_context:
    runs-on: ubuntu-latest
    container: andeo1812/gcc_check_gtest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - run: make test_context
  test_parsing:
    runs-on: ubuntu-latest
    container: andeo1812/gcc_check_gtest
    needs: [test_context]
    steps:
      - uses: actions/checkout@v2
      - run: make test_parsing;